### ISSUE TITLE
Describe how to set up the analyzers

### ISSUE THREAD

**Issue by nulltoken** [Wintellect/Wintellect.Analyzers#3]
Could you please update the README with a quick section explaining how to add and configure the analyzers in a CI environment?

**Comment by JohnWintellect** [comment]
Like any analyzers, install them through NuGet:

install-package Wintellect.Analyzers -Prerelease

That makes the analyzers part of the project forever so no matter where it's compiled, you're using them. Also, they are configured through Rulesets like those used with Code Analysis. Since VS 2015 is not finished it's a little rough around the edges.

**Comment by jwood803** [comment]
Should we wait until the official release of 2015 to document this?

**Comment by JohnWintellect** [comment]
Nope. :) The way to add analyzers to a project is set. It'd the Rulesets that are in a bit of flux until the next release of VS. Sorry for any confusion.

**Comment by tschlarm** [comment]
Are you planning on making this available in the Tools/Extensions and Updates window so it's available for all projects rather than having to install it on per project?
