### ISSUE TITLE
Predefined type analyzer

### ISSUE THREAD

**Issue by pjmagee** [Wintellect/Wintellect.Analyzers#4]
Why would I want to pick the defined types in System namespace when 99.9% of the code I see everywhere, on Github, at work...at my previous company all use the built in C# aliases.

Don't you find that using the built in System types can become a little confusing when comparing to important objects/structs in the Framework?

Using the C# pre-defined keyword seems much clearer to a developer that the person does indeed mean to use System.String when they use 'string'. 

What if I made a custom Object in my own namespace named Int32 or String like 

```
namespace PatrickMagee
{
       public class String 
       {


       }
}
```

Then used the return type String (from my namespace). 

Where is this Analyzer useful? :8ball:

**Comment by JohnWintellect** [comment]
Hi Patrick,

You do make some excellent points. The story behind this analyzer is that Jeffrey Richter and I were messing around with analyzers and we both subscribe to the theory he espoused in his book: you should always use an explicit type instead of an alias. It is more concrete and there's no surprise when doing PInvoke and such. Given how the world has gone all alias crazy maybe you are right. :smile:. You can always disable the rule in the Analyzer node. Maybe I should make it a suggestion instead of an error?

Thanks for the feedback and if you have any rule ideas I'd love to get them into Wintellect.Analyzers for you.

- John Robbins

**Comment by pjmagee** [comment]
Thanks for the reply, I just wanted to know if there was something more underlying behind the rule. As I'm currently writing some myself and came across yours, but i didn't understand the reason behind it. 

If you wanted these rules to become more mainstream I think making this particular rule more generalised as a Warning rather than an Error would be better.

Or possibly, only return a diagnostic warning in the situations where the System defined Type should be used in the scenarios that you have previously mentioned, such as using Win32 API with PInvoke extern signatures. 

This can be closed as now I know the reason behind why it's a rule.
